### ISSUE TITLE
tarFile argument is not shell escaped.

### ISSUE THREAD

**Issue by mikesamuel** [crookedneighbor/npm-unpack#22]
https://github.com/crookedneighbor/npm-unpack/blob/90fa07890c285db94e6969134d66157c599d5b01/lib/tar.js#L5 calls `child_process.exec` in shell mode, so a tarfile path that includes shell meta characters will break.

Specifically, a tarfile path like `"/dev/null; ls -l /etc/passwd"` will execute `ls -l /etc/passwd` and collect its output into stdout.

**Comment by crookedneighbor** [comment]
Would you like to open a PR?

**Comment by mikesamuel** [comment]
PR #23

**Comment by crookedneighbor** [comment]
Released with v0.1.1

Thanks!
